
output_dir: "/media/wang/SSD_2/demo/DECA_TR/pretrain/0315_convnextV2_b2K3_68_1080"
#tensorboard --logdir /media/wang/SSD_2/demo/DECA_TR/pretrain/0307_convnextV2_8_235_1080/logs
pretrained_modelpath: '/media/wang/SSD_2/demo/DECA/data/deca_model.tar'
#pretrained_modelpath: '/media/wang/SSD_1/demo/DECA_TR/pretrain/4090_convnextV2_16_235_0108_none/model.tar'

#数据集地址
facescape_dir: "/media/wang/SSD_2/Datasets/FaceScape/fmview_train_new"
small_facescape_dir: "/media/wang/SSD_2/Datasets/FaceScape/small_facescape_new"
vggface2_dir: "/media/wang/SSD_2/Datasets/vggface2"
lymh_dir: "/media/wang/SSD_2/Datasets/LYMH"


aflw2000_dir: "/media/wang/SSD_2/Datasets/AFLW2000/image/2"


dataset:
  training_data: ['small_facescape','facescape']
  eval_data: [ 'aflw2000' ]
  batch_size: 8
  K: 1
  isSingle: True
loss:
  photo: 0.0
  id: 0.
  useSeg: False
  shape_consistency: False
  lmk_num: 68 #注意修改aflw2000_dir
  lmk: 1.
  eyed: 1.0  #1.0.
  lipd: 0.3 #0.3
  id_shape_only: False
#  reg_shape: 1e-04
#  reg_exp: 6e-05
  reg_light: 0.
  reg_tex: 0.
  reg_jaw_pose: 0.

train:
  resume: True
  lr: 5e-4 #5e-4
  max_epochs: 10
  max_steps: 10000000
  log_steps: 200
  vis_steps: 200
  checkpoint_steps: 1000
  val_steps: 200
  eval_steps: 10000
model:
  E_flame_backbone: 'convnext_v2_tiny'
  n_shape: 100
  n_exp: 50

#resnet50 convnext_v1  convnext_v2_tiny convnext_v2_atto
