
output_dir: "/media/c723/SSD_1/demo/DECA_TR/pretrain/4090_convnextV2_16_235_0109"
pretrained_modelpath: '/media/c723/SSD_1/demo/data/deca_model.tar'

dataset:
  training_data: ['vggface2','lymh']
  batch_size: 16
  K: 1
loss:
  photo: 0.
  id: 0.
  useSeg: False
  shape_consistency: False
  lmk_num: 235
  lmk: 3.0
  eyed: 0.5  #1.0
  lipd: 0.5 #0.3

  reg_light: 0.3
  reg_tex: 0.

train:
  resume: True
  max_epochs: 50
  max_steps: 10000000
  log_steps: 100
  vis_steps: 200
  checkpoint_steps: 1500
  val_steps: 300
  eval_steps: 10000
  lr: 5e-4
  isSingle: True
model:
  E_flame_backbone: 'convnext_v2_tiny'
