
output_dir: "/media/c723/SSD_1/demo/DECA_TR/pretrain/0211_convnextV2_68_4090"
pretrained_modelpath: ''
#/media/c723/SSD_1/demo/DECA_TR/pretrain/4090_convnextV2_16_235_0118/model.tar
#数据集地址
facescape_dir: "/media/c723/SSD_1/Datasets/FaceScape/fmview_train"
small_facescape_dir: "/media/c723/SSD_1/Datasets/FaceScape/small_facescape"
vggface2_dir: "/media/c723/SSD_1/Datasets/vggface2"
lymh_dir: "/media/c723/SSD_1/Datasets/LYMH"
aflw2000_dir: "/media/c723/SSD_1/Datasets/AFLW2000/image/1"


dataset:
  training_data: ['small_facescape','vggface2','facescape']
  eval_data: [ 'aflw2000' ]
  batch_size: 16
  K: 1
  isSingle: True
loss:
  photo: 0.0
  id: 0.
  useSeg: False
  shape_consistency: False
  lmk_num: 68
  lmk: 1.
  eyed: 1.0  #1.0
  lipd: 0.3 #0.3
  id_shape_only: False
  reg_light: 0.
  reg_tex: 0.

train:
  resume: True
  lr: 5e-4 #5e-4
  max_epochs: 10
  max_steps: 10000000
  log_steps: 100
  vis_steps: 200
  checkpoint_steps: 1000
  val_steps: 300
  eval_steps: 10000
model:
  E_flame_backbone: 'convnext_v2_tiny'

#resnet50 convnext_v1  convnext_v2_tiny convnext_v2_atto
